In [23]:
import numpy as np

In [24]:
def read_the_edges(file_edge):
    edges = []
    with open(file_edge, 'r') as newfile:
        for line in newfile:
            source, target = line.strip().split()
            edges.append((source, target))
    return edges

In [25]:
def create_TransitionMatrix(edges):
    nodes = sorted(set(node for edge in edges for node in edge))     
    total_nodes = len(nodes)
    transition_matrix = np.zeros((total_nodes, total_nodes))
    
    node_index = {node: i for i, node in enumerate(nodes)}
    
    for edge in edges:
        startnode = node_index[edge[0]]
        endnode = node_index[edge[1]]
        transition_matrix[endnode, startnode] = 1
        transition_matrix[startnode, endnode] = 1
        
    valid_nodes = np.any(transition_matrix > 0, axis=0)

    transition_matrix = transition_matrix[valid_nodes][:, valid_nodes]
    return transition_matrix

input_file = "facebook_combined.txt" 

edges = read_the_edges(input_file)
transition_matrix = create_TransitionMatrix(edges)

print("Transition Matrix:")
print(transition_matrix)

Transition Matrix:
[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
def using_power_iteration(transition_matrix, total_iterations=100, damping_factor=0.85):
    total_nodes = transition_matrix.shape[0]
    rank_vector = np.ones(total_nodes) / total_nodes
    
    for _ in range(total_iterations):
        new_rv = np.dot(transition_matrix, rank_vector)
        new_rv = damping_factor * new_rv + (1 - damping_factor) / total_nodes
        if np.allclose(new_rv, rank_vector, atol=1e-6):
            break
        rank_vector = new_rv
    rank_vector /= np.sum(rank_vector)
    
    return rank_vector

page_ranks = using_power_iteration(transition_matrix)


print("\nPage Ranks:")
for node, rank in enumerate(page_ranks):
    print(f"Node {node}: Rank = {rank:.6f}")
    
print("Sum of PageRank values:", np.sum(page_ranks))


Page Ranks:
Node 0: Rank = 0.000002
Node 1: Rank = 0.000000
Node 2: Rank = 0.000000
Node 3: Rank = 0.000000
Node 4: Rank = 0.000000
Node 5: Rank = 0.000000
Node 6: Rank = 0.000000
Node 7: Rank = 0.000001
Node 8: Rank = 0.000001
Node 9: Rank = 0.000000
Node 10: Rank = 0.000001
Node 11: Rank = 0.000000
Node 12: Rank = 0.000000
Node 13: Rank = 0.000000
Node 14: Rank = 0.000000
Node 15: Rank = 0.000000
Node 16: Rank = 0.000000
Node 17: Rank = 0.000000
Node 18: Rank = 0.000003
Node 19: Rank = 0.000000
Node 20: Rank = 0.000000
Node 21: Rank = 0.000000
Node 22: Rank = 0.000001
Node 23: Rank = 0.000000
Node 24: Rank = 0.000000
Node 25: Rank = 0.000000
Node 26: Rank = 0.000000
Node 27: Rank = 0.000000
Node 28: Rank = 0.000000
Node 29: Rank = 0.000000
Node 30: Rank = 0.000001
Node 31: Rank = 0.000000
Node 32: Rank = 0.000001
Node 33: Rank = 0.000000
Node 34: Rank = 0.000002
Node 35: Rank = 0.000003
Node 36: Rank = 0.000002
Node 37: Rank = 0.000000
Node 38: Rank = 0.000000
Node 39: Rank = 0.0000

In [27]:
def write_outputfile(node_rankings, output_file):
    with open(output_file, 'w') as file:
        for node, rank in enumerate(node_rankings):
            file.write(f"Node {node}: Rank = {rank:.6f}\n")


In [28]:
input_file = "facebook_combined.txt"
output_file = "outputfile_5c.txt"
node_rankings = using_power_iteration(transition_matrix)
write_outputfile(node_rankings, output_file)
edges = read_the_edges(input_file)
transition_matrix = create_TransitionMatrix(edges)
sorted_indices = np.argsort(node_rankings)[::-1]

with open(output_file, 'w') as file:
    for i in sorted_indices:
        file.write(f"Node {i}: Rank = {node_rankings[i]:.6f}\n")

for i in sorted_indices:
    print(f"Node {i}: Rank = {node_rankings[i]:.6f}")


Node 1016: Rank = 0.006117
Node 1409: Rank = 0.005577
Node 1343: Rank = 0.005518
Node 1373: Rank = 0.005461
Node 1629: Rank = 0.005404
Node 1272: Rank = 0.005398
Node 1356: Rank = 0.005396
Node 1200: Rank = 0.005395
Node 1251: Rank = 0.005365
Node 1105: Rank = 0.005356
Node 1570: Rank = 0.005355
Node 1385: Rank = 0.005344
Node 1677: Rank = 0.005339
Node 1381: Rank = 0.005325
Node 1492: Rank = 0.005325
Node 1368: Rank = 0.005322
Node 1096: Rank = 0.005305
Node 1211: Rank = 0.005288
Node 1195: Rank = 0.005274
Node 1359: Rank = 0.005268
Node 1260: Rank = 0.005266
Node 1785: Rank = 0.005262
Node 1179: Rank = 0.005262
Node 1457: Rank = 0.005259
Node 1769: Rank = 0.005258
Node 1523: Rank = 0.005242
Node 1793: Rank = 0.005229
Node 1783: Rank = 0.005225
Node 1788: Rank = 0.005209
Node 1214: Rank = 0.005193
Node 1322: Rank = 0.005191
Node 1736: Rank = 0.005180
Node 1338: Rank = 0.005177
Node 1764: Rank = 0.005157
Node 1094: Rank = 0.005155
Node 1053: Rank = 0.005153
Node 1499: Rank = 0.005150
N