In [77]:
import numpy as np

In [78]:
def read_the_edges(file_edge):
    edges = []
    with open(file_edge, 'r') as newfile:
        for line in newfile:
            source, target = line.strip().split()
            edges.append((source, target))
    return edges

In [79]:
def create_TransitionMatrix(edges):
    nodes = sorted(set(node for edge in edges for node in edge))     
    total_nodes = len(nodes)
    transition_matrix = np.zeros((total_nodes, total_nodes))
    
    node_index = {node: i for i, node in enumerate(nodes)}
    
    for edge in edges:
        startnode = node_index[edge[0]]
        endnode = node_index[edge[1]]
        transition_matrix[endnode, startnode] = 1
    
    return transition_matrix

input_file = "LinkAnalysis_edgelist.txt" 

edges = read_the_edges(input_file)
transition_matrix = create_TransitionMatrix(edges)

print("Transition Matrix:")
print(transition_matrix)


Transition Matrix:
[[0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [80]:
def using_power_iteration(transition_matrix, total_iterations=100, damping_factor=0.85):
    total_nodes = transition_matrix.shape[0]
    rank_vector = np.ones(total_nodes) / total_nodes
    
    for _ in range(total_iterations):
        new_rv = np.dot(transition_matrix, rank_vector)
        new_rv = damping_factor * new_rv + (1 - damping_factor) / total_nodes
        if np.allclose(new_rv, rank_vector, atol=1e-6):
            break
        rank_vector = new_rv
    rank_vector /= np.sum(rank_vector)
    
    return rank_vector

page_ranks = using_power_iteration(transition_matrix)


print("\nPage Ranks:")
for node, rank in enumerate(page_ranks):
    print(f"Node {node}: Rank = {rank:.6f}")
    


Page Ranks:
Node 0: Rank = 0.187526
Node 1: Rank = 0.112540
Node 2: Rank = 0.279389
Node 3: Rank = 0.067539
Node 4: Rank = 0.153072
Node 5: Rank = 0.199934
Node 6: Rank = 0.000000


In [81]:
def write_outputfile(node_rankings, output_file):
    with open(output_file, 'w') as file:
        for node, rank in enumerate(node_rankings):
            file.write(f"Node {node}: Rank = {rank:.6f}\n")


In [82]:
input_file = "LinkAnalysis_edgelist.txt" 
output_file = "outputfile_5b.txt"  
node_rankings = using_power_iteration(transition_matrix)
write_outputfile(node_rankings, output_file)

sorted_indices = np.argsort(node_rankings)[::-1]

with open(output_file, 'w') as file:
    for i in sorted_indices:
        file.write(f"Node {i}: Rank = {node_rankings[i]:.6f}\n")

for i in sorted_indices:
    print(f"Node {i}: Rank = {node_rankings[i]:.6f}")


Node 2: Rank = 0.279389
Node 5: Rank = 0.199934
Node 0: Rank = 0.187526
Node 4: Rank = 0.153072
Node 1: Rank = 0.112540
Node 3: Rank = 0.067539
Node 6: Rank = 0.000000
